name: Autograding Tests
'on': [push, pull_request]
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: tests
      id: tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: tests
        # AFEGIM --build i un check de salut / sleep
        setup-command: |
          docker compose up -d --build
          echo "Esperant que els serveis estiguin llestos..."
          sleep 15
        command: docker exec bdda_api sh -c "pytest"
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS_RESULTS: "${{steps.tests.outputs.result}}"
      with:
        runners: tests