apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: PostgreSQL
    url: postgreSQL:5432
    user: postgres
    database: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: postgres
      sslmode: disable
      postgresVersion: 1400
    isDefault: true

  - name: Prometheus
    type: prometheus
    uid: Prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: false

  - name: Redis
    type: redis-datasource
    uid: Redis
    url: redis://redis:6379
    isDefault: false

  - name: Elasticsearch
    type: elasticsearch
    uid: Elasticsearch
    url: http://elasticsearch:9200
    jsonData:
      index: "incident_reports"
      timeField: "timestamp"
      esVersion: "8.0.0"
      maxConcurrentShardRequests: 5
    isDefault: false
