# Generated by Django 5.2 on 2025-05-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="partidas_ganadas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="partidas_jugadas",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
